spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
  mail:
    properties:
      from: sender@example.com
app:
  verification:
    code:
      expiry-minutes: 15
  require-email-verification: true

logging:
  level:
    root: WARN
    com.ramesh.lex_events: DEBUG